import { browser } from '$app/environment';
export const appState = $state({
  user: null,
  token: browser ? localStorage.getItem('token') : null,
  username: browser ? localStorage.getItem('username') : null,
  friends: [],
  dms: [],
  groups: [],
  requests: [],
  sentRequests: [],
  offlineFriends: [],
  profileCache: {},
  statusCache: {},
  savedMedia: [],
  unreadMessages: {},
  friendLastMsg: {},
  servers: [],
  serverGroups: {},
  serverChannels: {},
  serverGroupChannels: {},
  serverMembers: {},
  messages: [],
  currentChat: null,
  activeServerId: null,
  messageReactions: {},
  onlineUsers: new Set(),
  isTyping: {},
  hiddenDms: new Set(),
  recentlyUsedEmojis: browser ? JSON.parse(localStorage.getItem('recentEmojis') || '[]') : [],
});
export const uiState = $state({
  initialLoading: true,
  pendingReply: null,
  editingMessage: null,
  isSending: false,
  viewingProfile: null,
  isUploading: false,
  pendingFileUrl: null,
  sidebarOpen: true,
  mobileSidebarOpen: false,
});
